spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sportconnect
    username: postgres
    password: sportconnect
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  secret: "4dc74a91b7650c633c3765b809a9d3d0"
  expiration: 3600000
